# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_auto_20180305_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='file_name',
            field=models.CharField(max_length=40),
        ),
    ]
